parameters:
    darvin_content.filterer.class: Darvin\ContentBundle\Filterer\Filterer

services:
    _defaults:
        public: true

    darvin_content.filterer:
        class: '%darvin_content.filterer.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '@darvin_content.translatable.manager'
            - '@darvin_content.translatable.translation_joiner'
