parameters:
    darvin_content.slug.handler.unique.class: Darvin\ContentBundle\Slug\UniqueSlugHandler

    darvin_content.slug.map_item_factory.class: Darvin\ContentBundle\Slug\SlugMapItemFactory

    darvin_content.slug.map_rebuild_command.class: Darvin\ContentBundle\Command\SlugMapRebuildCommand
    darvin_content.slug.map_rebuild_command.name:  darvin:content:slug-map:rebuild

    darvin_content.slug.map_subscriber.class: Darvin\ContentBundle\EventListener\SlugMapSubscriber
    
    darvin_content.slug.rebuild_command.class: Darvin\ContentBundle\Command\RebuildSlugsCommand
    darvin_content.slug.rebuild_command.name:  darvin:content:slugs:rebuild

services:
    darvin_content.slug.handler.unique:
        class: "%darvin_content.slug.handler.unique.class%"
        tags:
            - { name: darvin_utils.slug_handler }

    darvin_content.slug.map_item_factory:
        class:  "%darvin_content.slug.map_item_factory.class%"
        public: false
        arguments:
            - "@property_accessor"

    darvin_content.slug.map_rebuild_command:
        class: "%darvin_content.slug.map_rebuild_command.class%"
        arguments:
            - "%darvin_content.slug.map_rebuild_command.name%"
            - "@doctrine.orm.entity_manager"
            - "@darvin_utils.mapping.metadata_factory"
            - "@darvin_content.slug.map_item_factory"
        tags:
            - { name: console.command }

    darvin_content.slug.map_subscriber:
        class: "%darvin_content.slug.map_subscriber.class%"
        arguments:
            - "@darvin_utils.mapping.metadata_factory"
            - "@darvin_content.slug.map_item_factory"
        tags:
            - { name: doctrine.event_subscriber, priority: 100 }
            - { name: kernel.event_listener,     event: darvin_utils.post_slugs_update, method: postSlugsUpdate }

    darvin_content.slug.rebuild_command:
        class: "%darvin_content.slug.rebuild_command.class%"
        arguments:
            - "%darvin_content.slug.rebuild_command.name%"
            - "@doctrine.orm.entity_manager"
            - "@darvin_utils.mapping.metadata_factory"
            - "@property_accessor"
            - "@darvin_utils.sluggable.manager"
        tags:
            - { name: console.command }
