parameters:
    darvin_content.sluggable.subscriber.class: Darvin\ContentBundle\EventListener\SluggableSubscriber

services:
    darvin_content.sluggable.subscriber:
        class: %darvin_content.sluggable.subscriber.class%
        arguments:
            - "@darvin_utils.mapping.metadata_factory"
            - "@property_accessor"
        tags:
            - { name: doctrine.event_subscriber }
