parameters:
    darvin_content.slug.handler.unique.class: Darvin\ContentBundle\Slug\UniqueSlugHandler

    darvin_content.slug.map_item_factory.class: Darvin\ContentBundle\Slug\SlugMapItemFactory

    darvin_content.slug.map_subscriber.class: Darvin\ContentBundle\EventListener\SlugMapSubscriber

services:
    _defaults:
        public: true

    darvin_content.slug.handler.unique:
        class: "%darvin_content.slug.handler.unique.class%"
        tags:
            - { name: darvin_utils.slug_handler }

    darvin_content.slug.map_item_factory:
        class:  "%darvin_content.slug.map_item_factory.class%"
        public: false
        arguments:
            - "@property_accessor"

    darvin_content.slug.map_subscriber:
        class: "%darvin_content.slug.map_subscriber.class%"
        arguments:
            - "@darvin_utils.mapping.metadata_factory"
            - "@darvin_content.slug.map_item_factory"
        tags:
            - { name: doctrine.event_subscriber, priority: 100 }
            - { name: kernel.event_listener,     event: darvin_utils.sluggable.slugs_updated, method: slugsUpdated }
