parameters:
    darvin_content.slug_map.item_factory.class: Darvin\ContentBundle\Slug\SlugMapItemFactory

    darvin_content.slug_map.router.class: Darvin\ContentBundle\Slug\SlugMapRouter

    darvin_content.slug_map.subscriber.class: Darvin\ContentBundle\EventListener\SlugMapSubscriber

services:
    _defaults:
        public: true

    darvin_content.slug_map.item_factory:
        class:  '%darvin_content.slug_map.item_factory.class%'
        public: false
        arguments:
            - '@property_accessor'

    darvin_content.slug_map.router:
        class: '%darvin_content.slug_map.router.class%'
        arguments:
            - '@router'
            - '@darvin_utils.homepage.router'
            - darvin_content_show

    darvin_content.slug_map.subscriber:
        class: '%darvin_content.slug_map.subscriber.class%'
        arguments:
            - '@darvin_utils.orm.entity_resolver'
            - '@darvin_utils.mapping.metadata_factory'
            - '@darvin_content.slug_map.item_factory'
        tags:
            - { name: doctrine.event_subscriber, priority: 100 }
            - { name: kernel.event_listener,     event: darvin_utils.sluggable.slugs_updated, method: slugsUpdated }
