parameters:
    darvin_content.sorting.sorted_by_entity_joiner.class: Darvin\ContentBundle\Sorting\SortedByEntityJoiner

services:
    darvin_content.sorting.sorted_by_entity_joiner:
        class: %darvin_content.sorting.sorted_by_entity_joiner.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@darvin_content.translatable.manager"
            - "@darvin_content.translatable.translation_joiner"
