parameters:
    darvin_content.widget.embedder.class: Darvin\ContentBundle\Widget\WidgetEmbedder

    darvin_content.widget.embedder.http_exception_event_subscriber.class: Darvin\ContentBundle\EventListener\Widget\Embedder\HttpExceptionSubscriber

    darvin_content.widget.embedder.redirect_event_subscriber.class: Darvin\ContentBundle\EventListener\Widget\Embedder\RedirectSubscriber

    darvin_content.widget.list_command.class: Darvin\ContentBundle\Command\ListWidgetsCommand
    darvin_content.widget.list_command.name:  darvin:content:widget:list

    darvin_content.widget.pool.class: Darvin\ContentBundle\Widget\WidgetPool

    darvin_content.widget.twig_extension.class: Darvin\ContentBundle\Twig\Extension\WidgetExtension

    darvin_content.widget.validator.name_unique.class: Darvin\ContentBundle\Validator\WidgetNameUniqueValidator

services:
    darvin_content.widget.embedder:
        class: "%darvin_content.widget.embedder.class%"
        arguments:
            - "@request_stack"
            - "@darvin_content.widget.pool"
        tags:
            - { name: darvin_utils.providable }

    darvin_content.widget.embedder.http_exception_event_subscriber:
        class: "%darvin_content.widget.embedder.http_exception_event_subscriber.class%"
        tags:
            - { name: kernel.event_subscriber }

    darvin_content.widget.embedder.redirect_event_subscriber:
        class: "%darvin_content.widget.embedder.redirect_event_subscriber.class%"
        tags:
            - { name: kernel.event_subscriber }

    darvin_content.widget.list_command:
        class: "%darvin_content.widget.list_command.class%"
        arguments:
            - "%darvin_content.widget.list_command.name%"
            - "@request_stack"
            - "@darvin_content.widget.pool"
        tags:
            - { name: console.command }

    darvin_content.widget.pool:
        class: "%darvin_content.widget.pool.class%"
        arguments:
            - "%darvin_content.widgets.blacklist%"
        tags:
            - { name: darvin_utils.providable }

    darvin_content.widget.twig_extension:
        class:  "%darvin_content.widget.twig_extension.class%"
        public: false
        arguments:
            - "@darvin_content.widget.embedder.provider"
            - "@darvin_content.widget.pool.provider"
        tags:
            - { name: twig.extension }

    darvin_content.widget.validator.name_unique:
        class: "%darvin_content.widget.validator.name_unique.class%"
        arguments:
            - "@darvin_content.widget.pool"
        tags:
            - { name: validator.constraint_validator, alias: darvin_content_widget_name_unique }
