parameters:
    darvin_content.admin.form.type.content_reference.choice.class: Darvin\ContentBundle\Form\Type\Admin\ContentReferenceChoiceType

    darvin_content.admin.view.widget.content_reference.class: Darvin\ContentBundle\Admin\View\ContentReferenceWidget

services:
    darvin_content.admin.form.type.content_reference.choice:
        class: '%darvin_content.admin.form.type.content_reference.choice.class%'
        arguments:
            - '@service_container'
            - '@darvin_content.reference.object.loader'
            - '@doctrine.orm.entity_manager'
            - '@darvin_admin.entity_namer'
            - '@darvin_utils.orm.entity_resolver'
            - '@darvin_admin.metadata.manager'
            - '@property_accessor'
            - '@darvin_admin.metadata.sort_criteria_detector'
            - '@stof_doctrine_extensions.listener.tree'
        tags:
            - { name: form.type }

    darvin_content.admin.view.widget.content_reference:
        class:  '%darvin_content.admin.view.widget.content_reference.class%'
        parent: darvin_admin.view.widget.abstract
        arguments:
            - '@darvin_admin.entity_namer'
            - '@darvin_admin.view.widget.show_link'
            - '@translator'
        tags:
            - { name: darvin_admin.view_widget }
