parameters:
    darvin_content.admin.widget.factory.forward_to_controller.class: Darvin\ContentBundle\Widget\Admin\ForwardToController\ForwardToControllerWidgetFactory

services:
    darvin_content.admin.widget.factory.forward_to_controller:
        class: '%darvin_content.admin.widget.factory.forward_to_controller.class%'
        arguments:
            - '@http_kernel'
            - '@request_stack'
            - '%darvin_content.widget.forward_to_controller%'
        tags:
            - { name: darvin_content.widget_factory }