parameters:
    darvin_content.autocomplete.autocompleter.class: Darvin\ContentBundle\Autocomplete\Autocompleter

    darvin_content.autocomplete.controller.class: Darvin\ContentBundle\Controller\AutocompleteController

    darvin_content.autocomplete.form_type.class: Darvin\ContentBundle\Form\Type\Autocomplete\AutocompleteType

services:
    Darvin\ContentBundle\Autocomplete\AutocompleterInterface: '@darvin_content.autocomplete.autocompleter'

    darvin_content.autocomplete.autocompleter:
        class: '%darvin_content.autocomplete.autocompleter.class%'
        arguments:
            - '@darvin_utils.callback.runner'
            - '@darvin_utils.locale.provider'
            - '%darvin_content.autocomplete.providers%'

    darvin_content.autocomplete.controller:
        class: '%darvin_content.autocomplete.controller.class%'
        tags:
            - { name: controller.service_arguments }

    darvin_content.autocomplete.form_type:
        class: '%darvin_content.autocomplete.form_type.class%'
        arguments:
            - '@router'
        tags:
            - { name: form.type }
