parameters:
    darvin_content.canonical_url.generator.class: Darvin\ContentBundle\CanonicalUrl\CanonicalUrlGenerator

    darvin_content.canonical_url.twig_extension.class: Darvin\ContentBundle\Twig\Extension\CanonicalUrlExtension

services:
    darvin_content.canonical_url.generator:
        class: '%darvin_content.canonical_url.generator.class%'
        arguments:
            - '@request_stack'
            - '@router'
            - '%darvin_content.canonical_url.parameter_whitelist%'

    darvin_content.canonical_url.twig_extension:
        class: '%darvin_content.canonical_url.twig_extension.class%'
        arguments:
            - '@darvin_content.canonical_url.generator'
        tags:
            - { name: twig.extension }
