parameters:
    darvin_content.content.twig.extension.class: Darvin\ContentBundle\Twig\Extension\ContentExtension

services:
    darvin_content.content.twig.extension:
        class: '%darvin_content.content.twig.extension.class%'
        tags:
            - { name: twig.extension }
