parameters:
    darvin_content.controller.front.class: Darvin\ContentBundle\Controller\FrontController

    darvin_content.controller_registry.class: Darvin\ContentBundle\Controller\ContentControllerRegistry

services:
    Darvin\ContentBundle\Controller\ContentControllerRegistryInterface: '@darvin_content.controller_registry'

    darvin_content.controller_pool:
        alias:      darvin_content.controller_registry
        deprecated: '"%alias_id%" is deprecated. Use "darvin_content.controller_registry" instead.'

    darvin_content.controller.front:
        class: '%darvin_content.controller.front.class%'
        arguments:
            - '@darvin_content.controller_registry'
            - '@doctrine.orm.entity_manager'
            - '@router'
            - '@darvin_content.translatable.translation_joiner'
        tags:
            - { name: controller.service_arguments }

    darvin_content.controller_registry:
        class: '%darvin_content.controller_registry.class%'
