parameters:
    darvin_content.controller.pool.class: Darvin\ContentBundle\Controller\ContentControllerPool

services:
    _defaults:
        public: true

    darvin_content.controller.pool:
        class: '%darvin_content.controller.pool.class%'
