parameters:
    darvin_content.filterer.class: Darvin\ContentBundle\Filterer\Filterer

services:
    Darvin\ContentBundle\Filterer\FiltererInterface: '@darvin_content.filterer'

    darvin_content.filterer:
        class: '%darvin_content.filterer.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '@darvin_content.translatable.translation_joiner'
