parameters:
    darvin_content.pagination.page_not_found_exception_subscriber.class: Darvin\ContentBundle\EventListener\Pagination\PageNotFoundExceptionSubscriber

    darvin_content.pagination.pager_subscriber.class: Darvin\ContentBundle\EventListener\Pagination\PagerSubscriber

services:
    _defaults:
        public: true

    darvin_content.pagination.page_not_found_exception_subscriber:
        class: '%darvin_content.pagination.page_not_found_exception_subscriber.class%'
        tags:
            - { name: kernel.event_subscriber }

    darvin_content.pagination.pager_subscriber:
        class: '%darvin_content.pagination.pager_subscriber.class%'
        arguments:
            - '@request_stack'
        tags:
            - { name: knp_paginator.subscriber }
