parameters:
    darvin_content.property.embedder.class: Darvin\ContentBundle\Property\Embedder\PropertyEmbedder

services:
    Darvin\ContentBundle\Property\Embedder\PropertyEmbedderInterface: '@darvin_content.property.embedder'

    darvin_content.property.embedder:
        class: '%darvin_content.property.embedder.class%'
        arguments:
            - '@darvin_utils.callback.runner'
            - '@doctrine.orm.entity_manager'
            - '@darvin_utils.locale.provider'
            - '@property_accessor'
            - '@darvin_utils.stringifier'
            - '%darvin_content.property.embedder.callbacks%'
