parameters:
    darvin_content.router.content_reference.class: Darvin\ContentBundle\Router\ContentReferenceRouter

    darvin_content.router.entity.class: Darvin\ContentBundle\Router\EntityRouter

services:
    Darvin\ContentBundle\Router\ContentReferenceRouterInterface: '@darvin_content.router.content_reference'
    Darvin\ContentBundle\Router\EntityRouterInterface:           '@darvin_content.router.entity'

    darvin_content.router.content_reference:
        class: '%darvin_content.router.content_reference.class%'
        arguments:
            - '@router'
            - '@darvin_utils.homepage.router'

    darvin_content.router.entity:
        class: '%darvin_content.router.entity.class%'
        arguments:
            - '@darvin_content.router.content_reference'
            - '@doctrine.orm.entity_manager'
            - '@darvin_utils.orm.entity_resolver'
