parameters:
    darvin_content.slug_map.subscriber.class: Darvin\ContentBundle\EventListener\SlugMapSubscriber

services:
    darvin_content.slug_map.subscriber:
        class: '%darvin_content.slug_map.subscriber.class%'
        arguments:
            - '@darvin_content.reference.factory'
            - '@darvin_utils.orm.entity_resolver'
            - '@darvin_utils.mapping.metadata_factory'
        tags:
            - { name: doctrine.event_subscriber, priority: 100 }
            - { name: kernel.event_listener,     event: darvin_utils.sluggable.slugs_updated, method: slugsUpdated }
