parameters:
    darvin_content.slug.handler.unique.class: Darvin\ContentBundle\Slug\UniqueSlugHandler

services:
    darvin_content.slug.handler.unique:
        class: '%darvin_content.slug.handler.unique.class%'
        tags:
            - { name: darvin_utils.slug_handler }
