parameters:
    darvin_content.slug_map.item_factory.class: Darvin\ContentBundle\Slug\SlugMapItemFactory

    darvin_content.slug_map.object_loader.class: Darvin\ContentBundle\Slug\SlugMapObjectLoader

    darvin_content.slug_map.subscriber.class: Darvin\ContentBundle\EventListener\SlugMapSubscriber

services:
    darvin_content.slug_map.item_factory:
        class: '%darvin_content.slug_map.item_factory.class%'
        arguments:
            - '@property_accessor'

    darvin_content.slug_map.object_loader:
        class: '%darvin_content.slug_map.object_loader.class%'
        arguments:
            - '@darvin_utils.custom_object.loader'
            - '@darvin_utils.locale.provider'
            - '@darvin_content.translatable.translation_joiner'
        calls:
            - [ setImageJoiner, [ '@?darvin_image.orm.image_joiner' ] ]

    darvin_content.slug_map.subscriber:
        class: '%darvin_content.slug_map.subscriber.class%'
        arguments:
            - '@darvin_utils.orm.entity_resolver'
            - '@darvin_utils.mapping.metadata_factory'
            - '@darvin_content.slug_map.item_factory'
        tags:
            - { name: doctrine.event_subscriber, priority: 100 }
            - { name: kernel.event_listener,     event: darvin_utils.sluggable.slugs_updated, method: slugsUpdated }
