parameters:
    darvin_content.sorting.attribute.renderer.class: Darvin\ContentBundle\Sorting\AttributeRenderer

    darvin_content.sorting.attribute.twig.extension.class: Darvin\ContentBundle\Twig\Extension\Sorting\AttributeExtension

    darvin_content.sorting.controller.reposition.class: Darvin\ContentBundle\Controller\Sorting\RepositionController

    darvin_content.sorting.repositioner.class: Darvin\ContentBundle\Sorting\Reposition\Repositioner

    darvin_content.sorting.security.voter.reposition.class: Darvin\ContentBundle\Security\Voter\Sorting\RepositionVoter

    darvin_content.sorting.sorter.class: Darvin\ContentBundle\Sorting\Sorter

    darvin_content.sorting.sorter.twig.extension.class: Darvin\ContentBundle\Twig\Extension\Sorting\SorterExtension

services:
    darvin_content.sorting.attribute.renderer:
        class: '%darvin_content.sorting.attribute.renderer.class%'
        arguments:
            - '@security.authorization_checker'
            - '@doctrine.orm.entity_manager'
            - '@request_stack'
            - '@router'

    darvin_content.sorting.attribute.twig.extension:
        class: '%darvin_content.sorting.attribute.twig.extension.class%'
        arguments:
            - '@darvin_content.sorting.attribute.renderer'
        tags:
            - { name: twig.extension }

    darvin_content.sorting.controller.reposition:
        class: '%darvin_content.sorting.controller.reposition.class%'
        arguments:
            - '@form.factory'
            - '@darvin_content.sorting.repositioner'
        tags:
            - { name: controller.service_arguments }

    darvin_content.sorting.repositioner:
        class: '%darvin_content.sorting.repositioner.class%'
        arguments:
            - '@security.authorization_checker'
            - '@darvin_utils.orm.entity_resolver'
            - '@doctrine.orm.entity_manager'

    darvin_content.sorting.security.voter.reposition:
        class: '%darvin_content.sorting.security.voter.reposition.class%'
        arguments:
            - '@security.authorization_checker'
            - '%darvin_content.sorting.reposition.required_permissions%'
        tags:
            - { name: security.voter }

    darvin_content.sorting.sorter:
        class: '%darvin_content.sorting.sorter.class%'
        arguments:
            - '@darvin_utils.orm.entity_resolver'
            - '@doctrine.orm.entity_manager'
            - '@request_stack'

    darvin_content.sorting.sorter.twig.extension:
        class: '%darvin_content.sorting.sorter.twig.extension.class%'
        arguments:
            - '@darvin_content.sorting.sorter'
        tags:
            - { name: twig.extension }
