parameters:
    darvin_content.sorting.attribute_renderer.class: Darvin\ContentBundle\Sorting\AttributeRenderer

    darvin_content.sorting.controller.reposition.class: Darvin\ContentBundle\Controller\Sorting\RepositionController

    darvin_content.sorting.repositioner.class: Darvin\ContentBundle\Sorting\Reposition\Repositioner

    darvin_content.sorting.security.voter.reposition.class: Darvin\ContentBundle\Security\Voter\Sorting\RepositionVoter

    darvin_content.sorting.sort_entity_joiner.class: Darvin\ContentBundle\Sorting\SortEntityJoiner

    darvin_content.sorting.sorter.class: Darvin\ContentBundle\Sorting\Sorter

    darvin_content.sorting.twig_extension.class: Darvin\ContentBundle\Twig\Extension\SortingExtension

services:
    darvin_content.sorting.attribute_renderer:
        class: '%darvin_content.sorting.attribute_renderer.class%'
        arguments:
            - '@security.authorization_checker'
            - '@security.csrf.token_manager'
            - '@doctrine.orm.entity_manager'
            - '@request_stack'
            - '@router'

    darvin_content.sorting.controller.reposition:
        class: '%darvin_content.sorting.controller.reposition.class%'
        arguments:
            - '@form.factory'
            - '@darvin_content.sorting.repositioner'
        tags:
            - { name: controller.service_arguments }

    darvin_content.sorting.repositioner:
        class: '%darvin_content.sorting.repositioner.class%'
        arguments:
            - '@security.authorization_checker'
            - '@doctrine.orm.entity_manager'

    darvin_content.sorting.security.voter.reposition:
        class: '%darvin_content.sorting.security.voter.reposition.class%'
        arguments:
            - '@security.authorization_checker'
            - '%darvin_content.sorting.reposition.required_permissions%'
        tags:
            - { name: security.voter }

    darvin_content.sorting.sort_entity_joiner:
        class: '%darvin_content.sorting.sort_entity_joiner.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@darvin_content.translatable.manager'
            - '@darvin_content.translatable.translation_joiner'

    darvin_content.sorting.sorter:
        class:  '%darvin_content.sorting.sorter.class%'
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@request_stack'

    darvin_content.sorting.twig_extension:
        class: '%darvin_content.sorting.twig_extension.class%'
        arguments:
            - '@darvin_content.sorting.attribute_renderer'
            - '@darvin_content.sorting.sorter'
        tags:
            - { name: twig.extension }
