parameters:
    darvin_content.translatable.event_subscriber.map.class: Darvin\ContentBundle\EventListener\Translatable\MapSubscriber

    darvin_content.translatable.event_subscriber.refresh_updated_at.class: Darvin\ContentBundle\EventListener\Translatable\RefreshUpdatedAtSubscriber

    darvin_content.translatable.event_subscriber.set_locales.class: Darvin\ContentBundle\EventListener\Translatable\SetLocalesSubscriber

    darvin_content.translatable.locale_setter.class: Darvin\ContentBundle\Translatable\TranslatableLocaleSetter

    darvin_content.translatable.manager.class: Darvin\ContentBundle\Translatable\TranslatableManager

    darvin_content.translatable.translation_initializer.class: Darvin\ContentBundle\Translatable\TranslationInitializer

    darvin_content.translatable.translation_joiner.class: Darvin\ContentBundle\Translatable\TranslationJoiner

services:
    darvin_content.translatable.event_subscriber.map:
        class:                 '%darvin_content.translatable.event_subscriber.map.class%'
        decorates:             Knp\DoctrineBehaviors\EventSubscriber\TranslatableEventSubscriber
        decoration_on_invalid: null
        arguments:
            - '@darvin_utils.orm.entity_resolver'
        tags:
            - { name: doctrine.event_subscriber }

    darvin_content.translatable.event_subscriber.refresh_updated_at:
        class: '%darvin_content.translatable.event_subscriber.refresh_updated_at.class%'
        arguments:
            - '@darvin_utils.mapping.metadata_factory'
            - '@property_accessor'
        tags:
            - { name: doctrine.event_subscriber }

    darvin_content.translatable.event_subscriber.set_locales:
        class: '%darvin_content.translatable.event_subscriber.set_locales.class%'
        arguments:
            - '@darvin_content.translatable.locale_setter'
        tags:
            - { name: doctrine.event_subscriber }

    darvin_content.translatable.locale_setter:
        class: '%darvin_content.translatable.locale_setter.class%'
        arguments:
            - '@darvin_utils.locale.provider'

    darvin_content.translatable.manager:
        class: '%darvin_content.translatable.manager.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: darvin_utils.providable }

    darvin_content.translatable.translation_initializer:
        class: '%darvin_content.translatable.translation_initializer.class%'
        arguments:
            - '@darvin_content.translatable.locale_setter'
            - '%locales%'

    darvin_content.translatable.translation_joiner:
        class: '%darvin_content.translatable.translation_joiner.class%'
        arguments:
            - '@darvin_utils.locale.provider'
