parameters:
    darvin_content.translatable.event_subscriber.class: Darvin\ContentBundle\EventListener\TranslatableSubscriber

    darvin_content.translatable.manager.class: Darvin\ContentBundle\Translatable\TranslatableManager

    darvin_content.translatable.refresh_updated_at_event_subscriber.class: Darvin\ContentBundle\EventListener\RefreshTranslatableUpdatedAtSubscriber

    darvin_content.translatable.translation_initializer.class: Darvin\ContentBundle\Translatable\TranslationInitializer

    darvin_content.translatable.translation_joiner.class: Darvin\ContentBundle\Translatable\TranslationJoiner

services:
    darvin_content.translatable.event_subscriber:
        class: '%darvin_content.translatable.event_subscriber.class%'
        arguments:
            - '@darvin_utils.orm.entity_resolver'
            - '@darvin_utils.locale.provider'
        tags:
            - { name: doctrine.event_subscriber }

    darvin_content.translatable.manager:
        class: '%darvin_content.translatable.manager.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: darvin_utils.providable }

    darvin_content.translatable.refresh_updated_at_event_subscriber:
        class: '%darvin_content.translatable.refresh_updated_at_event_subscriber.class%'
        arguments:
            - '@darvin_utils.mapping.metadata_factory'
            - '@property_accessor'
            - '@darvin_content.translatable.manager'
        tags:
            - { name: doctrine.event_subscriber }

    darvin_content.translatable.translation_initializer:
        class: '%darvin_content.translatable.translation_initializer.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@darvin_content.translatable.manager'
            - '@darvin_content.translatable.event_subscriber'

    darvin_content.translatable.translation_joiner:
        class: '%darvin_content.translatable.translation_joiner.class%'
        arguments:
            - '@darvin_utils.locale.provider'
            - '@darvin_content.translatable.manager'
