parameters:
    darvin_content.widget.embedder.class: Darvin\ContentBundle\Widget\Embedder\WidgetEmbedder

    darvin_content.widget.embedder.http_exception_event_subscriber.class: Darvin\ContentBundle\EventListener\Widget\Embedder\HttpExceptionSubscriber

    darvin_content.widget.embedder.redirect_event_subscriber.class: Darvin\ContentBundle\EventListener\Widget\Embedder\RedirectSubscriber

    darvin_content.widget.registry.class: Darvin\ContentBundle\Widget\WidgetRegistry

    darvin_content.widget.twig_extension.class: Darvin\ContentBundle\Twig\Extension\WidgetExtension

services:
    darvin_content.widget.pool:
        alias:      darvin_content.widget.registry
        deprecated: '"%alias_id%" is deprecated. Use "darvin_content.widget.registry" instead.'

    darvin_content.widget.pool.provider:
        alias:      darvin_content.widget.registry.provider
        deprecated: '"%alias_id%" is deprecated. Use "darvin_content.widget.registry.provider" instead.'

    darvin_content.widget.embedder:
        class: '%darvin_content.widget.embedder.class%'
        arguments:
            - '@request_stack'
            - '@darvin_content.widget.pool'
        tags:
            - { name: darvin_utils.providable }

    darvin_content.widget.embedder.http_exception_event_subscriber:
        class: '%darvin_content.widget.embedder.http_exception_event_subscriber.class%'
        tags:
            - { name: kernel.event_subscriber }

    darvin_content.widget.embedder.redirect_event_subscriber:
        class: '%darvin_content.widget.embedder.redirect_event_subscriber.class%'
        tags:
            - { name: kernel.event_subscriber }

    darvin_content.widget.registry:
        class: '%darvin_content.widget.registry.class%'
        arguments:
            - '%darvin_content.widget.blacklist%'
        tags:
            - { name: darvin_utils.providable }

    darvin_content.widget.twig_extension:
        class: '%darvin_content.widget.twig_extension.class%'
        arguments:
            - '@darvin_content.widget.embedder.provider'
            - '@darvin_content.widget.pool.provider'
        tags:
            - { name: twig.extension }
