parameters:
    darvin_content.widget.embedder.class: Darvin\ContentBundle\Widget\Embedder\WidgetEmbedder

    darvin_content.widget.embedder.event_subscriber.http_exception.class: Darvin\ContentBundle\EventListener\Widget\Embedder\HttpExceptionSubscriber

    darvin_content.widget.embedder.event_subscriber.redirect.class: Darvin\ContentBundle\EventListener\Widget\Embedder\RedirectSubscriber

    darvin_content.widget.embedder.twig.extension.class: Darvin\ContentBundle\Twig\Extension\Widget\EmbedderExtension

    darvin_content.widget.registry.class: Darvin\ContentBundle\Widget\WidgetRegistry

    darvin_content.widget.registry.twig.extension.class: Darvin\ContentBundle\Twig\Extension\Widget\RegistryExtension

services:
    Darvin\ContentBundle\Widget\Embedder\WidgetEmbedderInterface: '@darvin_content.widget.embedder'
    Darvin\ContentBundle\Widget\WidgetRegistryInterface:          '@darvin_content.widget.registry'

    darvin_content.widget.pool:
        alias:      darvin_content.widget.registry
        deprecated: '"%alias_id%" is deprecated. Use "darvin_content.widget.registry" instead.'

    darvin_content.widget.pool.provider:
        alias:      darvin_content.widget.registry.provider
        deprecated: '"%alias_id%" is deprecated. Use "darvin_content.widget.registry.provider" instead.'

    darvin_content.widget.embedder:
        class: '%darvin_content.widget.embedder.class%'
        arguments:
            - '@request_stack'
            - '@darvin_content.widget.registry'
        tags:
            - { name: darvin_utils.providable }

    darvin_content.widget.embedder.event_subscriber.http_exception:
        class: '%darvin_content.widget.embedder.event_subscriber.http_exception.class%'
        tags:
            - { name: kernel.event_subscriber }

    darvin_content.widget.embedder.event_subscriber.redirect:
        class: '%darvin_content.widget.embedder.event_subscriber.redirect.class%'
        tags:
            - { name: kernel.event_subscriber }

    darvin_content.widget.embedder.twig.extension:
        class: '%darvin_content.widget.embedder.twig.extension.class%'
        arguments:
            - '@darvin_content.widget.embedder.provider'
        tags:
            - { name: twig.extension }

    darvin_content.widget.registry:
        class: '%darvin_content.widget.registry.class%'
        arguments:
            - '%darvin_content.widget.blacklist%'
        tags:
            - { name: darvin_utils.providable }

    darvin_content.widget.registry.twig.extension:
        class: '%darvin_content.widget.registry.twig.extension.class%'
        arguments:
            - '@darvin_content.widget.registry.provider'
        tags:
            - { name: twig.extension }
