parameters:
    darvin_content.reference.rebuild.command.class: Darvin\ContentBundle\Command\Reference\RebuildCommand

services:
    darvin_content.reference.rebuild.command:
        class: '%darvin_content.reference.rebuild.command.class%'
        arguments:
            - '@darvin_content.reference.factory'
            - '@doctrine.orm.entity_manager'
            - '@darvin_utils.mapping.metadata_factory'
        tags:
            - { name: console.command }
