parameters:
    darvin_content.slug.rebuild_command.class: Darvin\ContentBundle\Command\RebuildSlugsCommand
    darvin_content.slug.rebuild_command.name:  darvin:content:slugs:rebuild

services:
    darvin_content.slug.rebuild_command:
        class: '%darvin_content.slug.rebuild_command.class%'
        arguments:
            - '%darvin_content.slug.rebuild_command.name%'
            - '@doctrine.orm.entity_manager'
            - '@darvin_utils.mapping.metadata_factory'
            - '@property_accessor'
            - '@darvin_utils.sluggable.manager'
        tags:
            - { name: console.command }
