parameters:
    darvin_content.translatable.translation.create.command.class: Darvin\ContentBundle\Command\Translation\CreateCommand

    darvin_content.translatable.translation.create.creator.class: Darvin\ContentBundle\Translatable\TranslationCreator

services:
    darvin_content.translatable.translation.create.command:
        class: '%darvin_content.translatable.translation.create.command.class%'
        arguments:
            - '@darvin_content.translatable.translation.create.creator'
        tags:
            - { name: console.command }

    darvin_content.translatable.translation.create.creator:
        class: '%darvin_content.translatable.translation.create.creator.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%locale%'
