parameters:
    darvin_content.widget.list.command.class: Darvin\ContentBundle\Command\Widget\ListCommand

services:
    darvin_content.widget.list.command:
        class: '%darvin_content.widget.list.command.class%'
        arguments:
            - '@request_stack'
            - '@darvin_content.widget.pool'
        tags:
            - { name: console.command }
