menu:
    group: seo

order_by:
    name: asc

searchable_fields:
    - name
    - title
    - value

sortable_fields:
    name:  ~
    title: translations.title
    value: translations.value

view:
    index:
        fields:
            name:  ~
            title: ~
            value: ~

form:
    edit:
        fields:
            name:
                options:
                    help: global_property.help.name
            translations:
                type: A2lix\TranslationFormBundle\Form\Type\TranslationsType
                options:
                    fields:
                        title:
                            help: global_property.help.title
                            attr:
                                required: true
                        value:
                            help: global_property.help.value
    filter:
        fields:
            name:
                compare_strict: false
            title:
                compare_strict: false
            value:
                compare_strict: false
