parameters:
    darvin_content.translatable.translations_create_command.class: Darvin\ContentBundle\Command\TranslationsCreateCommand
    darvin_content.translatable.translations_create_command.name:  darvin:content:translations:create

services:
    _defaults:
        public: true

    darvin_content.translatable.translations_create_command:
        class: "%darvin_content.translatable.translations_create_command.class%"
        arguments:
            - "%darvin_content.translatable.translations_create_command.name%"
            - "@doctrine.orm.entity_manager"
            - "@darvin_content.translatable.manager"
            - "%locale%"
        tags:
            - { name: console.command }
