parameters:
    darvin_content.widget.list_command.class: Darvin\ContentBundle\Command\ListWidgetsCommand
    darvin_content.widget.list_command.name:  darvin:content:widget:list

services:
    _defaults:
        public: true

    darvin_content.widget.list_command:
        class: "%darvin_content.widget.list_command.class%"
        arguments:
            - "%darvin_content.widget.list_command.name%"
            - "@request_stack"
            - "@darvin_content.widget.pool"
        tags:
            - { name: console.command }
