darvin_content_show:
    path:         /{slug}/
    defaults:     { _controller: Darvin\ContentBundle\Controller\ContentFrontController::showAction }
    requirements: { slug: '((([0-9a-z]+-{1})*[0-9a-z]+)+(/{1}(([0-9a-z]+-{1})*[0-9a-z]+)+)*)+' }
    methods:      [ get ]
