darvin_content_locale_switch:
    path:         /{locale}/switch
    defaults:     { _controller: darvin_content.locale.switch.controller }
    requirements: { locale: \w+ }
    methods:      [ get ]
